In [61]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os

In [62]:
activity_data = pd.read_csv("Outputs/output_file_acc.csv")
activity_data.head()
activity_data.Profile = pd.Categorical(activity_data.Profile)
activity_data['Profile_code'] = activity_data.Profile.cat.codes
activity_data.Activity = pd.Categorical(activity_data.Activity)
activity_data['Activity'] = activity_data.Activity.cat.codes

clean_data = activity_data.drop("Profile", axis=1)
clean_data = clean_data.drop("Date_time", axis=1)

clean_data["Profile_code"].unique()
#activity_data["Profile"].unique()
clean_data.describe()
clean_data.dtypes
clean_data.dropna()

              X         Y         Z          ts  Activity  Profile_code
0      0.190048 -0.078262 -0.986176  1578568648         4             5
1      0.140366 -0.068359 -0.998215  1578568648         4             5
2      0.003952 -0.032806 -0.969467  1578568648         4             5
3     -0.010345  0.084564 -0.947189  1578568648         4             5
4      0.116348 -0.303986 -1.067520  1578568648         4             5
5     -0.000671 -0.137405 -1.044846  1578568649         4             5
6      0.063049 -0.173904 -0.735840  1578568649         4             5
7      0.210770 -0.360046 -0.824387  1578568649         4             5
8      0.191986 -0.285980 -0.646591  1578568649         4             5
9      0.561478  0.138397 -0.424805  1578568649         4             5
10     0.997681  0.281937 -0.559769  1578568649         4             5
11     1.194824  0.484772 -0.537949  1578568649         4             5
12     1.128098  0.463547 -0.031113  1578568649         4             5
13     1.042465  0.415253  0.481384  1578568649         4             5
14     0.602737  0.716034  0.028870  1578568649         4             5
15     0.735657  0.777939 -0.113083  1578568650         4             5
16     0.772568  0.719696 -0.002777  1578568650         4             5
17     0.759186  0.648758  0.075470  1578568650         4             5
18     0.761490  0.639984  0.089279  1578568650         4             5
19     0.767105  0.681030  0.050110  1578568650         4             5
20     0.742523  0.668137  0.068253  1578568650         4             5
21     0.737732  0.662216  0.008682  1578568650         4             5
22     0.716766  0.648071  0.043274  1578568650         4             5
23     0.792175  0.633102 -0.003052  1578568650         4             5
24     0.763641  0.625381 -0.002457  1578568650         4             5
25     0.796555  0.638718  0.029755  1578568651         4             5
26     0.743683  0.602646  0.049454  1578568651         4             5
27     0.800293  0.688583 -0.040024  1578568651         4             5
28     0.717361  0.681122 -0.001404  1578568651         4             5
29     0.785049  0.667526 -0.005066  1578568651         4             5
...         ...       ...       ...         ...       ...           ...
72284  0.656113  0.244385 -0.045700  1578602474         2             7
72285  2.190125  0.264313 -0.273972  1578602474         2             7
72286  0.156006  0.010696 -0.345261  1578602474         2             7
72287  0.307404  0.112839  0.282715  1578602474         2             7
72288  1.534042  0.022736  0.323624  1578602474         2             7
72289  1.249451  0.173462 -0.177780  1578602474         2             7
72290  1.147568  0.690704  0.209686  1578602474         2             7
72291  0.849731 -0.003204 -0.519669  1578602475         2             7
72292  0.389404 -0.298264 -0.013412  1578602475         2             7
72293  0.466614 -0.051865  0.143219  1578602475         2             7
72294  1.473480 -0.714371 -0.140579  1578602475         2             7
72295  1.309967 -0.001953 -0.215866  1578602475         2             7
72296  0.847961 -0.304474 -0.667343  1578602475         2             7
72297  1.278397 -0.031677 -0.160797  1578602475         2             7
72298  0.839798 -0.138474 -0.384216  1578602475         2             7
72299  0.630692 -0.085800 -0.601013  1578602475         2             7
72300  0.335297  0.152237 -0.745071  1578602475         2             7
72301  0.510849  0.247498 -1.441223  1578602476         2             7
72302  0.091202 -0.144943 -0.852280  1578602476         2             7
72303  0.058823 -0.197830 -0.770447  1578602476         2             7
72304  0.282593 -0.526520 -0.818405  1578602476         2             7
72305  0.105957 -0.311005 -1.114227  1578602476         2             7
72306  0.045074 -0.299286 -1.047775  1578602476         2             7
72307  0.176361 -0.104843 -1.073456  1578602476         2             7
72308  0.306152 -0.118271 -0.980804  1578602476         2             7
72309  0.229660 -0.306976 -0.616196  1578602476         2             7
72310  0.477432 -0.313843 -0.884964  1578602476         2             7
72311  0.475784 -0.318481 -0.922211  1578602477         2             7
72312  0.545731 -0.384033 -0.996078  1578602477         2             7
72313  0.697006 -0.338638 -0.765015  1578602477         2             7

[72314 rows x 6 columns]

In [63]:
# Assign X (data) and y (target)
X = clean_data.drop("Activity", axis=1)
y = clean_data["Activity"]
print(X.shape, y.shape)

(72314, 5) (72314,)

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [65]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [66]:
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [67]:
X_train.head()

              X          Y         Z          ts  Profile_code
21481  0.349350   5.462814  8.197815  1578503520             0
21909  0.349350   5.462814  8.197815  1578503580             0
68780 -0.128189  -0.912155 -0.386810  1578580403             7
37418 -0.748947 -11.837296 -1.261017  1578511560             0
55178 -0.011841   0.098312 -0.992691  1578667069             3

In [68]:
 classifier.fit(X_train, y_train)

C:\Users\mghan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\mghan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [69]:
 LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [70]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.41211394855720473
Testing Data Score: 0.41213562697051825

In [71]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [3 3 3 3 3 3 3 3 3 3]
First 10 Actual labels: [4, 4, 5, 2, 5, 0, 4, 0, 4, 3]

In [72]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

       Prediction  Actual
0               3       4
1               3       4
2               3       5
3               3       2
4               3       5
5               3       0
6               3       4
7               3       0
8               3       4
9               3       3
10              3       3
11              3       2
12              3       3
13              3       3
14              3       3
15              3       4
16              3       4
17              3       2
18              3       5
19              3       3
20              3       3
21              3       5
22              3       0
23              3       3
24              3       5
25              3       3
26              3       1
27              3       3
28              3       1
29              3       4
...           ...     ...
18049           3       1
18050           3       1
18051           3       3
18052           3       3
18053           3       5
18054           3       2
18055           3       3
18056           3       0
18057           3       1
18058           3       3
18059           3       4
18060           3       3
18061           3       1
18062           3       1
18063           3       2
18064           3       0
18065           3       0
18066           3       0
18067           3       3
18068           3       3
18069           3       3
18070           3       4
18071           3       4
18072           3       3
18073           3       3
18074           3       2
18075           3       0
18076           3       5
18077           3       3
18078           3       3

[18079 rows x 2 columns]